### ISSUE TITLE
dictionary nested in a list item

### ISSUE THREAD

**Issue by freddrake** [KenKundert/nestedtext#12]
The documentation seems to suggest that a list item can contain a nested dictionary:

> A value for a dictionary or list item may be a rest-of-line string as shown above,
> or it may be a nested dictionary, list or a multiline string. 
> (https://nestedtext.org/en/stable/how_to_write.html#nesting)

The example doesn't show an example of a dictionary nested into a list item, though.

The definition of a list item suggests that the value can only be a string:

> A list item is introduced with a dash at the start of a line. Anything that follows
> the space after the dash is the value and is treated as a string.
> (https://nestedtext.org/en/stable/how_to_write.html#lists)

Is it possible to nest a dictionary inside a list item?  An example would be very helpful.

**Comment by KenKundert** [comment]
Yes, it is possible for for list to hold dictionaries and visa versa. I have refined documentation to make this more clear. As for an example, I modified the introductory example to illustrate this. You can see it [here](https://nestedtext.org/en/latest/index.html). There are now two treasurers.
