### ISSUE TITLE
[Request] There seems to be no info about file extension for nestedtext documents

### ISSUE THREAD

**Issue by sTiKyt** [KenKundert/nestedtext#19]
According to some examples it's ".nt" but i wasn't able to find that info anywhere else.

**Comment by asb** [comment]
There's some guidance on suffixes in the docs for the dump() function, but I agree it might make sense to have this elsewhere too https://nestedtext.org/en/stable/nestedtext.dump.html

**Comment by KenKundert** [comment]
Thanks for the suggestion. I have added a bit the the [basic use section](https://nestedtext.org/en/latest/basic_syntax.html#nestedtext-files).  Do you think that is sufficient?

**Comment by sTiKyt** [comment]
Yes, thank you
