### ISSUE TITLE
Patch version 2.0.1 - update 'v2.0' tag

### ISSUE THREAD

**Issue by LewisGaul** [KenKundert/nestedtext#27]
I'm not sure what was changed in v2.0.1 (since nothing is mentioned at https://nestedtext.org/en/latest/releases.html or https://nestedtext.org/en/latest/changelog.html) but the `v2.0` tag seems to still point at the old 2.0.0 commit, meaning https://nestedtext.org/en/v2.0/ still goes to v2.0.0.

Could this be updated (and perhaps something in the CI be tweaked to ensure this isn't missed in the future)?

**Comment by KenKundert** [comment]
Version 2.0.1 only involves some refactoring of the code, documentation, and tests.  The changes are small and do not affect users, and so are not mentioned in the documentation.  Instead, they are described in the commit message.

I do not change the tags to point to the latest version.  Thus, the v2.0 tag will always point to the same version.  Instead, I only tag releases, and releases always reset the patch level to 0.  Besides updating the minor and perhaps major level upon release, I also publish the code to PyPI and ReadTheDocs.   In this way, a release (a tagged version) is always consistent between GigHub, PyPI, and ReadTheDocs. Patch revisions like this one are treated as trial versions that are simply leading to the next release and are only expected to be used by developers that have cloned the git repository.  This contrasts with releases, that are expected to be adopted by users.

**Comment by LewisGaul** [comment]
Sorry, I forgot that the use of version numbers is somewhat non-standard, but this sounds like it makes sense for not updating the tag. I just got confused when 'latest' was showing me something different to '2.0' which I thought was latest!
