### ISSUE TITLE
New implementation

### ISSUE THREAD

**Issue by andrewchambers** [KenKundert/nestedtext#28]
Just an FYI, I did an implementation of the spec in the [Janet](https://janet-lang.org/) programming language:

https://github.com/andrewchambers/janet-nested-text

**Comment by KenKundert** [comment]
Thanks Andrew!

Do you think it is ready to share (relatively complete and tested, documented, commitment to support, etc)?  If so, I will add a link to it on the nestedtext.org site.

-Ken

**Comment by andrewchambers** [comment]
It passes the test suite except for one case, so i think it is relatively complete. It is a lesser known language, so could understand why you might not want to link it. 

w.r.t. support, do you think the spec is likely to change much in the future?

**Comment by KenKundert** [comment]
I am not expecting anymore changes to the language.  I have added a link to your project.

**Comment by KenKundert** [comment]
Andrew,
    I'd like to ask you a few things about your implementation of NestedText.

1. Do you feel it is suitable for other people to use?
2. Are you planning to support and enhance it long term?
3. Which version of the NestedText language do you support?  The original 
   version (v1.0 or the latest version (v3.0)?

The reason I ask is that your README looks pretty thin, and I am wondering if it 
makes sense for nestedtext.org to direct people to your github repository.

-Ken

**Comment by andrewchambers** [comment]
> 1. Do you feel it is suitable for other people to use?

If they use the janet programming language i think it would work fine for them.

> 2. Are you planning to support and enhance it long term?

My use case for it has changed so I am not working on it currently.

> 3. Which version of the NestedText language do you support?  The original
   version (v1.0 or the latest version (v3.0)?

It supports version 3.1.0 as that is the test suite it runs against.

**Comment by KenKundert** [comment]
Splendid. Thanks Andrew.
