### ISSUE TITLE
Info: Implementation in Go (Golang) available

### ISSUE THREAD

**Issue by npillmayer** [KenKundert/nestedtext#29]
Hi Ken,

I just wanted to point you to an implementation of NestedText in Go, available on Github at
https://github.com/npillmayer/nestext.
Would you be so kind as to include a link to it on NestedText's GitHub page and nestedtext.org?

Thank you for the great work!

--Norbert

**Comment by KenKundert** [comment]
Excellent. Thank you. I have added the link.
