### ISSUE TITLE
Add links to more NestedText implementations?

### ISSUE THREAD

**Issue by erikw** [KenKundert/nestedtext#33]
While I was browsing GitHub I discovered two more implementations that are currently not listed at
https://nestedtext.org/en/latest/related_projects.html,

* https://github.com/CoolMineman/nestedtext-java
* https://github.com/dolow/nt-go

that both pass the official tests. Maybe those can be included in the Related Projects page as well?

**Comment by KenKundert** [comment]
They have not reached out to me yet. Perhaps they are not ready yet.  I will reach out to them and see if they would like to go into the list.
Thanks!

**Comment by KenKundert** [comment]
I reached out, but neither responded.  Perhaps when they get further along.
