### ISSUE TITLE
Suggestion of clarification in the language reference documentation

### ISSUE THREAD

**Issue by RebelusQuo** [KenKundert/nestedtext#37]
Please excuse me for posting this as an issue rather than a PR, but I find it hard to motivate a fork just for minor changes to the documentation.

As I read through the document the Line-type tags section had me imagine a "tag" as a single character due to all the examples being one character. Later sections do more directly speak of them as a character followed by space or line break, but I would like to suggest the following for clarifications:

Under the Line-type tags section, change the numbered list:

> 1. the first of these specific characters when followed immediately by a space or line break: dash (`-␣`, `-↵`), colon (`:␣`, `:↵`), or greater-than symbol (`>␣`, `>↵`), or
> 2. the first non-white space character on a line being one of a hash (`#`), left bracket (`[`), or left brace (`{`).

Replace each occurrence of the phrase (for some `<char>`):
> by a space (`<char>␣`) or a line break

With:
> by a space or a line break (`<char>␣`, `<char>↵`)

**Comment by KenKundert** [comment]
I think I understand.  Let me work on that section to try to be more clear and consistent about what I mean by a tag.

**Comment by KenKundert** [comment]
Okay, I have updated the documentation in GitHub with the clarifications.
