### ISSUE TITLE
Consider adding a native JavaScript implementation

### ISSUE THREAD

**Issue by fidian** [KenKundert/nestedtext#48]
I wrote a native JavaScript implementation of NestedText. It's not a WASM build of a compiled project, so it is significantly lighter than the megabytes of JavaScript that the current linked project uses.

https://www.npmjs.com/package/nestedtext

https://github.com/fidian/nestedtext

It passes all of the current official tests.

**Comment by KenKundert** [comment]
Sorry for the late response, but I added this project to the related projects page some time ago.
