### ISSUE TITLE
No schema enforced

### ISSUE THREAD

**Issue by brunoborges** [KenKundert/nestedtext#5]

**Comment by KenKundert** [comment]
I don't know what you are requesting.

**Comment by KenKundert** [comment]
The schema is _every leaf value is a string_. If you do not want that, you can apply your own schema using [voluptuous](https://pypi.org/project/voluptuous).

**Comment by yunruse** [comment]
This is a good way to be for a data format!

IMO it would be useful to mention this in `readme.md` and close this issue.

**Comment by KenKundert** [comment]
Done.
