### ISSUE TITLE
Inline list does not work

### ISSUE THREAD

**Issue by dunsunik** [KenKundert/nestedtext#54]
I'm using version 3.7.
Just see my very simple code below:

```
  cont = """
  first: something
  animals: [dog, cat]
  """
  
  data = nt.loads(content=cont, top="dict", dialect="I")
  
  print(data)
```

It returns this:
{'first': 'something', 'animals': '[dog, cat]'}

**Comment by dunsunik** [comment]
Thank you !
That way it's working perfectly fine.
Though I would assume that when it's inline it means on one line. Anyways thanks for your nice work.
Cheers

**Comment by KenKundert** [comment]
Oh yeah, I guess the term inline is a bit misleading.  Perhaps we should have used one-line list and one-line dict.
